# Generated by Django 3.1.7 on 2021-04-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=100, verbose_name='Название оборудования')),
                ('voltage', models.IntegerField(verbose_name='Напряжение')),
                ('current', models.IntegerField(verbose_name='Ток')),
            ],
        ),
    ]
