# Generated by Django 3.1.7 on 2021-04-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('equipments', '0002_auto_20210405_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='questions',
            field=models.ManyToManyField(to='questions.QuestionYN', verbose_name='Название вопроса'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='current',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ток'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='voltage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Напряжение'),
        ),
    ]
