# Generated by Django 3.1.7 on 2021-04-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('equipments', '0003_auto_20210406_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='questionsMeasuring',
            field=models.ManyToManyField(to='questions.QuestionMeasuring', verbose_name='Название вопроса замера'),
        ),
    ]
