# Generated by Django 3.1.7 on 2021-04-08 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_remove_equipment_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='questionsMeasuring',
        ),
    ]
