# Generated by Django 3.1.7 on 2021-05-20 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
        ('equipments', '0007_remove_equipment_questionsmeasuring'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='factory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='factory.factory', verbose_name='Предприятие'),
        ),
    ]
