# Generated by Django 3.1.7 on 2021-04-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_remove_equipment_questions'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionYN',
        ),
        migrations.AddField(
            model_name='questionmeasuring',
            name='answer',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'Unknow')], default=2),
        ),
    ]
