# Generated by Django 3.1.7 on 2021-04-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_questionmeasuring_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionmeasuring',
            old_name='equipment_name',
            new_name='qeustion_name',
        ),
        migrations.AlterField(
            model_name='questionmeasuring',
            name='voltage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Допустимое отклонение от нормы, %'),
        ),
    ]
