# Generated by Django 3.1.7 on 2021-04-08 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0007_remove_equipment_questionsmeasuring'),
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='Equipment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='equipments.equipment'),
        ),
        migrations.AddField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
